[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[features]
default = []
with-tantivy = ["dep:tantivy"]

[dependencies]
anyhow.workspace = true
models = { path = "../models" }
tracing.workspace = true
tantivy = { version = "0.20.2", optional = true }
